PeerOrgs:
  - &School1
    Name: School1MSP
    Domain: school1.edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - &School2
    Name: School2MSP
    Domain: school2.edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
OrdererOrgs:
  - &EducationBoard
    Name: EducationBoardMSP
    Domain: board.edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
