PeerOrgs:
  - &School1
    Name: School1MSP
    Domain: school1.edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - &School2
    Name: School2MSP
    Domain: school2.edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - &EducationBureau
    Name: EducationBureauMSP
    Domain: bureau.edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
OrdererOrgs:
  - &EduOrderer
    Name: EduOrdererMSP
    Domain: edu.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
