# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer0.orderer.ssm.yeyu.tech:
  peer0.wdu.ssm.yeyu.tech:
  peer0.hgpu.ssm.yeyu.tech:
  peer0.edb.ssm.yeyu.tech:

networks:
  test:
    name: ssm

services:
  orderer0.orderer.ssm.yeyu.tech:
    container_name: orderer0.orderer.ssm.yeyu.tech
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.orderer.ssm.yeyu.tech:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/orderer.ssm.yeyu.tech/orderers/orderer0.orderer.ssm.yeyu.tech/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/orderer.ssm.yeyu.tech/orderers/orderer0.orderer.ssm.yeyu.tech/tls/:/var/hyperledger/orderer/tls
      - orderer0.orderer.ssm.yeyu.tech:/var/hyperledger/production/orderer
      - ./:/etc/hyperledger/peercfg
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - test

  peer0.edb.ssm.yeyu.tech:
    container_name: peer0.edb.ssm.yeyu.tech
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_PROFILE_ENABLED=false
      # Peer specific variables
      - CORE_PEER_ID=peer0.edb.ssm.yeyu.tech
      - CORE_PEER_ADDRESS=peer0.edb.ssm.yeyu.tech:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.edb.ssm.yeyu.tech:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.edb.ssm.yeyu.tech:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.edb.ssm.yeyu.tech:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.edb.ssm.yeyu.tech:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./crypto-config/peerOrganizations/edb.ssm.yeyu.tech/peers/peer0.edb.ssm.yeyu.tech:/etc/hyperledger/fabric
      - peer0.edb.ssm.yeyu.tech:/var/hyperledger/production
      - ./:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - test

  peer0.wdu.ssm.yeyu.tech:
    container_name: peer0.wdu.ssm.yeyu.tech
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_PROFILE_ENABLED=false
      # Peer specific variables
      - CORE_PEER_ID=peer0.wdu.ssm.yeyu.tech
      - CORE_PEER_ADDRESS=peer0.wdu.ssm.yeyu.tech:17051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_CHAINCODEADDRESS=peer0.wdu.ssm.yeyu.tech:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.wdu.ssm.yeyu.tech:17051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.wdu.ssm.yeyu.tech:17051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.wdu.ssm.yeyu.tech:19444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./crypto-config/peerOrganizations/wdu.ssm.yeyu.tech/peers/peer0.wdu.ssm.yeyu.tech:/etc/hyperledger/fabric
      - peer0.wdu.ssm.yeyu.tech:/var/hyperledger/production
      - ./:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 17051:17051
      - 19444:19444
    networks:
      - test

  peer0.hgpu.ssm.yeyu.tech:
    container_name: peer0.hgpu.ssm.yeyu.tech
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_PROFILE_ENABLED=false
      # Peer specific variables
      - CORE_PEER_ID=peer0.hgpu.ssm.yeyu.tech
      - CORE_PEER_ADDRESS=peer0.hgpu.ssm.yeyu.tech:17052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17052
      - CORE_PEER_CHAINCODEADDRESS=peer0.hgpu.ssm.yeyu.tech:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hgpu.ssm.yeyu.tech:17052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hgpu.ssm.yeyu.tech:17052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.hgpu.ssm.yeyu.tech:19444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./crypto-config/peerOrganizations/hgpu.ssm.yeyu.tech/peers/peer0.hgpu.ssm.yeyu.tech:/etc/hyperledger/fabric
      - peer0.hgpu.ssm.yeyu.tech:/var/hyperledger/production
      - ./:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 17052:17052
      - 19445:19444
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./:/opt/gopath/src/github.com/hyperledger/fabric/peer/cfg
      - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
    depends_on:
      - peer0.hgpu.ssm.yeyu.tech
      - peer0.wdu.ssm.yeyu.tech
      - peer0.edb.ssm.yeyu.tech
    networks:
      - test
